name: Create release

# Creating maven and github release

on:
  workflow_dispatch:
    inputs:
      release-version: # id of input
        description: "override default release version e.g. with 0.1.0-1"
        required: true

permissions:
  contents: write

env:
  dotnet-version: 8.x
  RELEASE_VERSION: ${{ github.event.inputs.release-version }}

jobs:
  build:
    name: "Build solution"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ env.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Build
        working-directory: cockpit-runner
        run: dotnet build
      - name: Dotnet Publish
        working-directory: cockpit-runner
        run: dotnet publish --sc true -r win-x64 -c Release
      - name: Create Release
        working-directory: cockpit-runner
        run: |
          echo "releasing with version ${{ env.RELEASE_VERSION }}"
          gh release create ${{ env.RELEASE_VERSION }} ./bin/Release/net8.0/win-x64/publish/*.exe
        env:
          GH_TOKEN: ${{ github.token }}

